name: facgure_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_maps_flutter: ^2.2.5
  geolocator: ^9.0.2
  flutter_polyline_points: ^1.0.0
  http: ^0.13.5
  sliding_up_panel: ^2.0.0+1
  skeletons: ^0.0.3
  flutter_rating_bar: ^4.0.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

